[project]
name = "socket-io"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi>=0.121.0",
    "pyinstaller>=6.16.0",
    "python-socketio>=5.14.3",
    "uvicorn>=0.38.0",
]
