---

type: dataset
config_id: 6b118e25-55a1-4767-bf3e-e6bda5669276
name: naturtyper_utvalgte_kalkmark_boreonemoral

metadata_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
layers:
- arcgis: '0'
  wms:
  - naturtype_utvalgt_omr
  result_status: HIT-RED
  planning_guidance_id: 39592497-57fc-418b-b3f1-8947aa8453b7
  filter: UtvalgtNaturtypeKode = 'UN07'
properties:
- Områdenavn
- UtvalgtNaturtype
- Nøyaktighetsklasse
- Registreringsdato
- Faktaark
themes:
- natur
