---

type: dataset
config_id: 980399fc-3d54-44f2-93e7-73a307670dcc
name: arter_nasjonal_forvaltningsinteresse

metadata_id: a8456aed-441a-40c4-831f-46bcbe4e6ff1
arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/artnasjonal2/MapServer
wms: https://kart.miljodirektoratet.no/arcgis/services/artnasjonal2/MapServer/WMSServer
layers:
- arcgis: '2'
  wms:
  - Alle_arter_av_sarlig_stor_forv_int_omr
  - Alle_arter_av_sarlig_stor_forv_int_pkt
- arcgis: '1'
  wms:
  - Alle_arter_av_sarlig_stor_forv_int_pkt
  - Alle_arter_av_sarlig_stor_forv_int_omr
  result_status: HIT-RED
properties:
- AntallObservasjoner
- Gruppe
- NorskNavn
- Status
- Faktaark
themes:
- natur
