---

type: dataset
config_id: e4e254b9-d3b6-45af-88a4-54382593e41d
name: naturtyper_utvalgte_kalksjøer

metadata_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
layers:
- arcgis: '0'
  wms:
  - naturtype_utvalgt_omr
  result_status: HIT-RED
  planning_guidance_id: 0f18bebe-9fe3-44dd-b6d1-b34e932ff438
  filter: UtvalgtNaturtypeKode = 'UN05'
properties:
- Områdenavn
- UtvalgtNaturtype
- Nøyaktighetsklasse
- Registreringsdato
- Faktaark
themes:
- natur
