---

type: dataset
config_id: 3a220fd3-2aa3-4c34-89aa-b41c07f6564d
name: naturvernomr√•der

metadata_id: 0e7eb17f-35ef-46d3-a465-3112d8bb2b5e
arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/vern/mapserver
wms: https://kart.miljodirektoratet.no/arcgis/services/vern/mapServer/WMSServer
layers:
- arcgis: '4'
  wms:
  - foreslatt_naturvern_omrade
  result_status: HIT-RED
  planning_guidance_id: 9dfd2c3a-bdf4-4d95-aad2-9ba37a522794
  building_guidance_id: d38864a8-03e9-4141-8a6b-a646941c7c2c
properties:
- navn
- faktaark
- verneform
- verneplan
- datafangstdato
- maalemetode
- noeyaktighet
themes:
- natur