---

type: dataset
config_id: 727e5e04-f403-4907-8644-ffcd68f3544c
name: geoteknisk_borehull
title: Geoteknisk borehull

metadata_id: bf45a463-434d-4b4d-84dc-9325780ab5fb
ogc_api: https://ogcapitest.ngu.no/rest/services/grunnundersokelser_utvidet/collections
wms: https://geo.ngu.no/geoserver/nadag/ows
layers:
- ogc_api: geotekniskborehull
  wms:
  - GB_filter_komplette_data
  result_status: HIT-YELLOW
geom_field: posisjon
properties:
- kvikkleirePåvisning
- antallBorehullUndersøkelser
- høyde
- maksBoretLengde
themes:
- geologi
