---

type: dataset
config_id: af961cfa-e0b2-4d4e-9560-f17913a7576c
name: hensynssone_energianlegg

metadata_id: 9f71a24b-9997-409f-8e42-ce6f0c62e073
wfs: https://wfs.geonorge.no/skwms1/wfs.nettanlegg
wms: https://nve.geodataonline.no/arcgis/services/Nettanlegg2/MapServer/WMSServer
layers:
- wfs: EL_Luftlinje
  wms:
  - Distribusjonsnett
  - Regionalnett
  result_status: HIT-RED
  planning_guidance_id: cc04ba06-1ad4-40cc-b961-389786a269ad
geom_field: linje
properties:
- navn
- nettniv√•
- spenning
themes:
- samfunnssikkerhet
