---

type: dataset
config_id: c24e0058-f555-4a47-b65b-4f011e64789e
name: faresone_kvikkleireskred

metadata_id: b2d5aaf8-79ac-40f3-9cd6-fdc30bc42ea1
arcgis: https://nve.geodataonline.no/arcgis/rest/services/SkredKvikkleire2/MapServer
wms: https://nve.geodataonline.no/arcgis/services/SkredKvikkleire2/MapServer/WMSServer
layers:
- arcgis: '1'
  wms:
  - KvikkleireRisiko
  result_status: HIT-RED
  planning_guidance_id: 1490d2ee-a5c6-4dfb-907a-44cb5022781b
  building_guidance_id: 2e84d54f-9e93-4559-8214-8cb21567fa04
properties:
- skredOmrNavn
- faregrad
- konsekvens
- risiko
- rapportURL
themes:
- samfunnssikkerhet
