---
disabled: true

type: dataset
name: steinsprang_aktsomhets_omr
config_id: df4d09fa-86bd-4efa-bbdf-39d5d7e65840

metadata_id: 02c6d51c-4e8c-4948-a620-dc046c8cb747 
arcgis: TODO - har ikke https://nve.geodataonline.no/arcgis/rest/services
wms: TODO - har ikke
layers:
- wfs: PotensieltSkredfareOmr
  wms:
  - Steinsprang-AktsomhetOmrader
  result_status: HIT-YELLOW
  planning_guidance_id: 2d405ce6-98ea-40f9-905b-f8a0d5c96224
  building_guidance_id: 2d405ce6-98ea-40f9-905b-f8a0d5c96224
geom_field: omr√•de
properties:
- skredType
- skredfareVurdering
- temaKvalitet
- oppdateringsdato
themes:
- samfunnssikkerhet
