---

type: dataset
config_id: 7914d4d9-8101-432e-ac36-ac086491f758
name: snoskred_aktsomhets_omr

metadata_id: 54ada9d8-e6fc-48d6-82b0-5477166a4aaa
wfs: https://wfs.geonorge.no/skwms1/wfs.snoskredaktsomhetsomrader
wms: https://nve.geodataonline.no/arcgis/services/SkredSnoAktR/MapServer/WMSServer
layers:
- wfs: PotensieltSkredfareOmr
  wms:
  - Snoskred-Aktsomhetsomrader
  result_status: HIT-YELLOW
  planning_guidance_id: 7831236b-c9c1-4d5f-af4b-cac0304d7d6e
  building_guidance_id: 7831236b-c9c1-4d5f-af4b-cac0304d7d6e
geom_field: omr√•de
properties:
- skredType
- skredfareVurdering
- temaKvalitet
- oppdateringsdato
themes:
- samfunnssikkerhet
