---

type: dataset
config_id: 0054b4a9-4bb5-4322-9ba6-6f9fd390ec9c
name: reindrift_oppsamlingsomr√•de

metadata_id: a02e84ec-322c-47a7-a626-ca02d57d1f7e
wfs: https://wfs02.nibio.no/cgi-bin/rein/oppsamlingsomrade
wms: https://reindrift.nibio.no/cgi-bin/reindrift
layers:
- wfs: Oppsamlingsomrade
  wms:
  - Oppsamling
  result_status: HIT-RED
geom_field: msGeometry
properties:
- distriktnavn
- beitebrukerstreng
- kvalitetssikret
- oppdateringsdato
themes:
- landbruk
