---

type: dataset
config_id: d1b8ace8-18c8-43e6-86f7-858b6d4d2a2e
name: reindrift_trekklei

metadata_id: 95b0d396-a6fe-462b-8753-120efd0b60f3
wfs: https://wfs02.nibio.no/cgi-bin/rein/trekklei
wms: https://reindrift.nibio.no/cgi-bin/reindrift
layers:
- wfs: Trekklei
  wms:
  - Trekklei
  result_status: HIT-RED
geom_field: msGeometry
properties:
- distriktnavn
- beitebrukerstreng
- kvalitetssikret
- oppdateringsdato
themes:
- landbruk
