---

type: dataset
config_id: bc713cf4-f4e5-42c4-9f58-eaccfab33f02
name: reindrift_reindriftsanlegg

metadata_id: 8dfa67c5-3099-4353-9ce0-72f9ebd44a2c
wfs: https://wfs02.nibio.no/cgi-bin/rein/reindriftsanlegg
wms: https://reindrift.nibio.no/cgi-bin/reindrift
layers:
- wfs: ReindriftsAnleggPunkt
  wms:
  - Anlegg
  result_status: HIT-RED
geom_field: msGeometry
properties:
- distriktnavn
- beitebrukerstreng
- kodenavn
- definisjon
- kvalitetssikret
- oppdateringsdato
themes:
- landbruk
